modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="mechanica"
version="0.1.0-dev.1"
displayName="Mechanica"
authors="Mechanica contributors"
description='''
Mechanica is a vanilla-styled medieval technology mod focused on practical mechanical construction systems.
The first development target is the Constructor, an energy-powered machine for placing and assembling structures from schematics.
'''

[[dependencies.mechanica]]
modId="neoforge"
type="required"
versionRange="[26.1.2.95,)"
ordering="NONE"
side="BOTH"

[[dependencies.mechanica]]
modId="minecraft"
type="required"
versionRange="[26.1.2,26.1.3)"
ordering="NONE"
side="BOTH"
